name: Project Board Automation [Code Review]
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add or update pull request in project board
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: "edgarcnp.dev"
          column-name: "Code Review"
          issue-number: ${{ github.event.pull_request.number }}
          project-location: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.PROJECT_BOARD_PAT }}
