jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project board
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECT_BOARD_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue.number;
            github = new Octokit({
              auth: process.env.GITHUB_TOKEN
            });
            github.projects.listForRepo({
              owner: owner,
              repo: repo
            }).then(projects => {
              const project = projects.data.find(project => project.name === 'edgarcnp.dev');
              if (!project) {
                console.log(`Project 'edgarcnp.dev' not found.`);
                return;
              }
              github.projects.listColumns({
                project_id: project.id
              }).then(columns => {
                const column = columns.data.find(column => column.name === 'Bug');
                if (!column) {
                  console.log(`Column 'Bug' not found in project '${project.name}'.`);
                  return;
                }
                github.projects.createProjectCard({
                  column_id: column.id,
                  content_id: issueNumber,
                  content_type: 'Issue'
                }).then(card => {
                  console.log(`Added issue ${issueNumber} to project board.`);
                }).catch(error => {
                  console.log(`Error adding issue ${issueNumber} to project board: ${error}`);
                });
              }).catch(error => {
                console.log(`Error listing columns for project ${project.name}: ${error}`);
              });
            }).catch(error => {
              console.log(`Error listing projects for repo ${owner}/${repo}: ${error}`);
            });
