name: Project Board Automation [Ready to Merge]
on:
  check_suite:
    types: [completed]
    branches:
      - main

jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Move pull request to Ready to Merge column
        uses: actions/github-script@v6
        if: ${{ github.event.check_suite.conclusion == 'success' }}
        with:
          github-token: ${{ secrets.PROJECT_BOARD_PAT }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({
              auth: `token ${process.env.GITHUB_TOKEN}`,
            });
            const { data: projects } = await octokit.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const project = projects.find(project => project.name === 'edgarcnp.dev');
            const { data: columns } = await octokit.projects.listColumns({
              project_id: project.id
            });
            const column = columns.find(column => column.name === 'Ready to Merge');
            const { data: cards } = await octokit.projects.listCards({
              column_id: column.id
            });
            const card = cards.find(card => card.content_url === context.payload.check_suite.pull_requests[0].url);
            if (card) {
              await octokit.projects.updateCard({
                card_id: card.id,
                column_id: column.id,
                note: context.payload.check_suite.pull_requests[0].title,
              });
            } else {
              await octokit.projects.createCard({
                column_id: column.id,
                content_id: context.payload.check_suite.pull_requests[0].id,
                content_type: 'PullRequest',
              });
            }
