name: Project Board Automation [Issue - Bug]
on:
  issues:
    types: [labeled]
    branches:
      - main

jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project board
        uses: actions/github-script@v6
        if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
        with:
          github-token: ${{ secrets.PROJECT_BOARD_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue.number;
            const projects = await github.projects.listForRepo({
              owner: owner,
              repo: repo
            });
            const project = projects.data.find(project => project.name === 'edgarcnp.dev');
            if (!project) {
              console.log(`Project 'edgarcnp.dev' not found.`);
              return;
            }
            const column = await github.projects.listColumns({
              project_id: project.id
            }).then(res => res.data.find(column => column.name === 'Bug'));
            if (!column) {
              console.log(`Column 'Bug' not found in project '${project.name}'.`);
              return;
            }
            const card = await github.projects.createProjectCard({
              column_id: column.id,
              content_id: issueNumber,
              content_type: 'Issue'
            });
            console.log(`Added issue ${issueNumber} to project board.`);
