name: Project Board Automation [Ready to Merge]
on:
  check_suite:
    types: [ completed ]
    branches:
      - main

jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Move pull request to Ready to Merge column
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: "edgarcnp.dev"
          column-name: "Ready to Merge"
          issue-number: ${{ github.event.pull_request.number }}
          project-location: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.PROJECT_BOARD_PAT }}