name: Project Board Automation [Issue - Bug]
on:
  issues:
    types: [labeled]

jobs:
  project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Add or update issue in project board
        uses: peter-evans/create-or-update-project-card@v2
        if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
        with:
          project-name: "edgarcnp.dev"
          column-name: "Bug"
          issue-number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          project-location: 'bottom'
